#!/bin/bash
set -e 

# gcc 
F90="gfortran"
CXX="g++"

# intel 
# CXX="icc"
# F90="ifort"

# SAC HOME
SACHOME=${HOME}/software//sac/

### STOP HERE ##########


# check input dir
if [[ $# -ne 1 ]]; then 
  echo "Usage: ./INSTALL.sh INSTALL_DIR"
  exit 1
fi
INSTALL_DIR=$1

# compile measure_adj
mkdir -p build
cd build
cmake .. -DCXX=$CXX -DFC=$F90 -DSACHOME=${SACHOME} -DPYTHON_EXECUTABLE=`which python`
make install -j4 
cd ..
rm -rf build 

# build python
pip install -e .

mkdir -p $INSTALL_DIR
\cp -r scripts/module_env scripts/*.sh plots fwat_params $INSTALL_DIR/
CDIR=`pwd`

chmod +x $INSTALL_DIR/*.sh 

echo " ============= " 
echo " Install Successfully!"
echo " ============= " 