#!/bin/bash
set -e 

# gcc 
F90="gfortran"
CXX="g++"

# intel 
# CXX="icc"
# F90="ifort"

# SAC HOME
SACHOME=${HOME}/software/sac/

### STOP HERE ##########


# check input dir
if [[ $# -ne 2 ]]; then 
  echo "Usage: ./INSTALL.sh SUBMIT_SYSTEM(slurm/pbs/local) INSTALL_DIR"
  exit 1
fi
SYSTEM=$1
INSTALL_DIR=$2

# compile measure_adj
mkdir -p build
cd build
cmake .. -DCXX=$CXX -DFC=$F90 -DSACHOME=${SACHOME} -DPYTHON_EXECUTABLE=`which python`
make install -j4 
cd ..
rm -rf build 

# build python
pip install -e .

mkdir -p $INSTALL_DIR
\cp -r scripts/module_env scripts/*.sh plots fwat_params $INSTALL_DIR/
CDIR=`pwd`

cd scripts
if [ "$SYSTEM" == "slurm" ]; then 
  cat slurm/slurm_tag_sem.sh sbash_forward.sh >  $INSTALL_DIR/sbash_forward.sh
  cat slurm/slurm_tag_sem.sh sbash_measure.sh >  $INSTALL_DIR/sbash_measure.sh
  cat slurm/slurm_tag_post.sh sbash_postproc_kl.sh > $INSTALL_DIR/sbash_postproc_kl.sh
  cat slurm/slurm_tag_post.sh sbash_wolfe.sh > $INSTALL_DIR/sbash_wolfe.sh
  \cp slurm/run_fwi.sh ../$INSTALL_DIR/
elif [ "$SYSTEM" == "local" ]; then 
  echo "#!/bin/bash\n" > tmp
  cat tmp sbash_forward.sh >  $INSTALL_DIR/sbash_forward.sh
  cat tmp sbash_measure.sh >  $INSTALL_DIR/sbash_measure.sh
  cat tmp sbash_postproc_kl.sh > $INSTALL_DIR/sbash_postproc_kl.sh
  cat tmp sbash_wolfe.sh > $INSTALL_DIR/sbash_wolfe.sh
  \rm tmp
  \cp local/run_fwi.sh $INSTALL_DIR/
else 
  echo "$SYSTEM is not implemented!"
  exit 1
fi 

cd ..


chmod +x $INSTALL_DIR/*.sh 

echo " ============= " 
echo " Install Successfully!"
echo " ============= " 