"""
AUTO-GENERATED by auto_kergen.py -- do not edit by hand.
Regenerate with:  python auto_kergen.py --write

Base <-> user model and kernel conversions for the dtti model type.
"""
import numpy as np


def cijkl2dtti_kltype1(model, backward=False):
    if not backward:
        model_new = np.zeros((5,) + model.shape[1:])
        model_new[0,...] = np.sqrt(model[0,...]/model[21,...])
        model_new[1,...] = np.sqrt(model[20,...]/model[21,...])
        model_new[2,...] = model[21,...]
        model_new[3,...] = (-1/2*model[15,...] + (1/2)*model[18,...])/model[20,...]
        model_new[4,...] = -model[16,...]/model[20,...]
    else:
        vp = model[0,...]
        vs = model[1,...]
        rho = model[2,...]
        gcp = model[3,...]
        gsp = model[4,...]
        model_new = np.zeros((22,) + model.shape[1:])
        model_new[0,...] = rho*vp**2
        model_new[1,...] = rho*vp**2 - 2*rho*vs**2
        model_new[2,...] = rho*vp**2 - 2*rho*vs**2
        model_new[6,...] = rho*vp**2
        model_new[7,...] = rho*vp**2 - 2*rho*vs**2
        model_new[11,...] = rho*vp**2
        model_new[15,...] = -gcp*rho*vs**2 + rho*vs**2
        model_new[16,...] = -gsp*rho*vs**2
        model_new[18,...] = gcp*rho*vs**2 + rho*vs**2
        model_new[20,...] = rho*vs**2
        model_new[21,...] = rho
    return model_new


def kl2dtti_kltype1(md_usr, md_kl):
    vp = md_usr[0,...]
    vs = md_usr[1,...]
    rho = md_usr[2,...]
    gcp = md_usr[3,...]
    gsp = md_usr[4,...]
    kl_opt = md_usr * 0
    kl_opt[0,...] = 2*rho*vp*md_kl[0,...] + 2*rho*vp*md_kl[11,...] + 2*rho*vp*md_kl[1,...] + 2*rho*vp*md_kl[2,...] + 2*rho*vp*md_kl[6,...] + 2*rho*vp*md_kl[7,...]
    kl_opt[1,...] = -2*gsp*rho*vs*md_kl[16,...] - 4*rho*vs*md_kl[1,...] + 2*rho*vs*md_kl[20,...] - 4*rho*vs*md_kl[2,...] - 4*rho*vs*md_kl[7,...] + (-2*gcp*rho*vs + 2*rho*vs)*md_kl[15,...] + (2*gcp*rho*vs + 2*rho*vs)*md_kl[18,...]
    kl_opt[2,...] = -gsp*vs**2*md_kl[16,...] + vp**2*md_kl[0,...] + vp**2*md_kl[11,...] + vp**2*md_kl[6,...] + vs**2*md_kl[20,...] + (vp**2 - 2*vs**2)*md_kl[1,...] + (vp**2 - 2*vs**2)*md_kl[2,...] + (vp**2 - 2*vs**2)*md_kl[7,...] + (-gcp*vs**2 + vs**2)*md_kl[15,...] + (gcp*vs**2 + vs**2)*md_kl[18,...] + md_kl[21,...]
    kl_opt[3,...] = -rho*vs**2*md_kl[15,...] + rho*vs**2*md_kl[18,...]
    kl_opt[4,...] = -rho*vs**2*md_kl[16,...]
    kl_opt[0:3,...] *= md_usr[0:3,...]
    return kl_opt


def cijkl2dtti_kltype2(model, backward=False):
    if not backward:
        model_new = np.zeros((8,) + model.shape[1:])
        model_new[0,...] = np.sqrt(model[0,...]/model[21,...])
        model_new[1,...] = np.sqrt(model[11,...]/model[21,...])
        model_new[2,...] = np.sqrt(model[20,...]/model[21,...])
        model_new[3,...] = np.sqrt(((1/2)*model[15,...] + (1/2)*model[18,...])/model[21,...])
        model_new[4,...] = model[21,...]
        model_new[5,...] = model[2,...]/(model[0,...] - model[15,...] - model[18,...])
        model_new[6,...] = (-1/2*model[15,...] + (1/2)*model[18,...])/((1/2)*model[15,...] + (1/2)*model[18,...])
        model_new[7,...] = -model[16,...]/((1/2)*model[15,...] + (1/2)*model[18,...])
    else:
        vph = model[0,...]
        vpv = model[1,...]
        vsh = model[2,...]
        vsv = model[3,...]
        rho = model[4,...]
        eta = model[5,...]
        gcp = model[6,...]
        gsp = model[7,...]
        model_new = np.zeros((22,) + model.shape[1:])
        model_new[0,...] = rho*vph**2
        model_new[1,...] = rho*vph**2 - 2*rho*vsh**2
        model_new[2,...] = eta*(rho*vph**2 - 2*rho*vsv**2)
        model_new[6,...] = rho*vph**2
        model_new[7,...] = eta*(rho*vph**2 - 2*rho*vsv**2)
        model_new[11,...] = rho*vpv**2
        model_new[15,...] = -gcp*rho*vsv**2 + rho*vsv**2
        model_new[16,...] = -gsp*rho*vsv**2
        model_new[18,...] = gcp*rho*vsv**2 + rho*vsv**2
        model_new[20,...] = rho*vsh**2
        model_new[21,...] = rho
    return model_new


def kl2dtti_kltype2(md_usr, md_kl):
    vph = md_usr[0,...]
    vpv = md_usr[1,...]
    vsh = md_usr[2,...]
    vsv = md_usr[3,...]
    rho = md_usr[4,...]
    eta = md_usr[5,...]
    gcp = md_usr[6,...]
    gsp = md_usr[7,...]
    kl_opt = md_usr * 0
    kl_opt[0,...] = 2*eta*rho*vph*md_kl[2,...] + 2*eta*rho*vph*md_kl[7,...] + 2*rho*vph*md_kl[0,...] + 2*rho*vph*md_kl[1,...] + 2*rho*vph*md_kl[6,...]
    kl_opt[1,...] = 2*rho*vpv*md_kl[11,...]
    kl_opt[2,...] = -4*rho*vsh*md_kl[1,...] + 2*rho*vsh*md_kl[20,...]
    kl_opt[3,...] = -4*eta*rho*vsv*md_kl[2,...] - 4*eta*rho*vsv*md_kl[7,...] - 2*gsp*rho*vsv*md_kl[16,...] + (-2*gcp*rho*vsv + 2*rho*vsv)*md_kl[15,...] + (2*gcp*rho*vsv + 2*rho*vsv)*md_kl[18,...]
    kl_opt[4,...] = eta*(vph**2 - 2*vsv**2)*md_kl[2,...] + eta*(vph**2 - 2*vsv**2)*md_kl[7,...] - gsp*vsv**2*md_kl[16,...] + vph**2*md_kl[0,...] + vph**2*md_kl[6,...] + vpv**2*md_kl[11,...] + vsh**2*md_kl[20,...] + (vph**2 - 2*vsh**2)*md_kl[1,...] + (-gcp*vsv**2 + vsv**2)*md_kl[15,...] + (gcp*vsv**2 + vsv**2)*md_kl[18,...] + md_kl[21,...]
    kl_opt[5,...] = (rho*vph**2 - 2*rho*vsv**2)*md_kl[2,...] + (rho*vph**2 - 2*rho*vsv**2)*md_kl[7,...]
    kl_opt[6,...] = -rho*vsv**2*md_kl[15,...] + rho*vsv**2*md_kl[18,...]
    kl_opt[7,...] = -rho*vsv**2*md_kl[16,...]
    kl_opt[0:5,...] *= md_usr[0:5,...]
    return kl_opt


def cijkl2dtti_kltype3(model, backward=False):
    if not backward:
        model_new = np.zeros((8,) + model.shape[1:])
        model_new[0,...] = np.sqrt((2/3)*model[0,...]/model[21,...] + (1/3)*model[11,...]/model[21,...])
        model_new[1,...] = np.sqrt((1/3)*((1/2)*model[15,...] + (1/2)*model[18,...])/model[21,...] + (2/3)*model[20,...]/model[21,...])
        model_new[2,...] = model[21,...]
        model_new[3,...] = (np.sqrt(model[0,...]/model[21,...]) - np.sqrt(model[11,...]/model[21,...]))/np.sqrt(model[11,...]/model[21,...])
        model_new[4,...] = (-np.sqrt(((1/2)*model[15,...] + (1/2)*model[18,...])/model[21,...]) + np.sqrt(model[20,...]/model[21,...]))/np.sqrt(((1/2)*model[15,...] + (1/2)*model[18,...])/model[21,...])
        model_new[5,...] = model[2,...]/(model[0,...] - model[15,...] - model[18,...])
        model_new[6,...] = (-1/2*model[15,...] + (1/2)*model[18,...])/((1/2)*model[15,...] + (1/2)*model[18,...])
        model_new[7,...] = -model[16,...]/((1/2)*model[15,...] + (1/2)*model[18,...])
    else:
        vp = model[0,...]
        vs = model[1,...]
        rho = model[2,...]
        kappaa = model[3,...]
        kappab = model[4,...]
        eta = model[5,...]
        gcp = model[6,...]
        gsp = model[7,...]
        model_new = np.zeros((22,) + model.shape[1:])
        model_new[0,...] = 3*rho*vp**2*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1)
        model_new[1,...] = 3*rho*vp**2*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1) - 6*rho*vs**2*(kappab + 1)**2/(2*(kappab + 1)**2 + 1)
        model_new[2,...] = eta*(3*rho*vp**2*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1) - 6*rho*vs**2/(2*(kappab + 1)**2 + 1))
        model_new[6,...] = 3*rho*vp**2*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1)
        model_new[7,...] = eta*(3*rho*vp**2*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1) - 6*rho*vs**2/(2*(kappab + 1)**2 + 1))
        model_new[11,...] = 3*rho*vp**2/(2*(kappaa + 1)**2 + 1)
        model_new[15,...] = -3*gcp*rho*vs**2/(2*(kappab + 1)**2 + 1) + 3*rho*vs**2/(2*(kappab + 1)**2 + 1)
        model_new[16,...] = -3*gsp*rho*vs**2/(2*(kappab + 1)**2 + 1)
        model_new[18,...] = 3*gcp*rho*vs**2/(2*(kappab + 1)**2 + 1) + 3*rho*vs**2/(2*(kappab + 1)**2 + 1)
        model_new[20,...] = 3*rho*vs**2*(kappab + 1)**2/(2*(kappab + 1)**2 + 1)
        model_new[21,...] = rho
    return model_new


def kl2dtti_kltype3(md_usr, md_kl):
    vp = md_usr[0,...]
    vs = md_usr[1,...]
    rho = md_usr[2,...]
    kappaa = md_usr[3,...]
    kappab = md_usr[4,...]
    eta = md_usr[5,...]
    gcp = md_usr[6,...]
    gsp = md_usr[7,...]
    kl_opt = md_usr * 0
    kl_opt[0,...] = 6*eta*rho*vp*(kappaa + 1)**2*md_kl[2,...]/(2*(kappaa + 1)**2 + 1) + 6*eta*rho*vp*(kappaa + 1)**2*md_kl[7,...]/(2*(kappaa + 1)**2 + 1) + 6*rho*vp*(kappaa + 1)**2*md_kl[0,...]/(2*(kappaa + 1)**2 + 1) + 6*rho*vp*(kappaa + 1)**2*md_kl[1,...]/(2*(kappaa + 1)**2 + 1) + 6*rho*vp*(kappaa + 1)**2*md_kl[6,...]/(2*(kappaa + 1)**2 + 1) + 6*rho*vp*md_kl[11,...]/(2*(kappaa + 1)**2 + 1)
    kl_opt[1,...] = -12*eta*rho*vs*md_kl[2,...]/(2*(kappab + 1)**2 + 1) - 12*eta*rho*vs*md_kl[7,...]/(2*(kappab + 1)**2 + 1) - 6*gsp*rho*vs*md_kl[16,...]/(2*(kappab + 1)**2 + 1) - 12*rho*vs*(kappab + 1)**2*md_kl[1,...]/(2*(kappab + 1)**2 + 1) + 6*rho*vs*(kappab + 1)**2*md_kl[20,...]/(2*(kappab + 1)**2 + 1) + (-6*gcp*rho*vs/(2*(kappab + 1)**2 + 1) + 6*rho*vs/(2*(kappab + 1)**2 + 1))*md_kl[15,...] + (6*gcp*rho*vs/(2*(kappab + 1)**2 + 1) + 6*rho*vs/(2*(kappab + 1)**2 + 1))*md_kl[18,...]
    kl_opt[2,...] = eta*(3*vp**2*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1) - 6*vs**2/(2*(kappab + 1)**2 + 1))*md_kl[2,...] + eta*(3*vp**2*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1) - 6*vs**2/(2*(kappab + 1)**2 + 1))*md_kl[7,...] - 3*gsp*vs**2*md_kl[16,...]/(2*(kappab + 1)**2 + 1) + 3*vp**2*(kappaa + 1)**2*md_kl[0,...]/(2*(kappaa + 1)**2 + 1) + 3*vp**2*(kappaa + 1)**2*md_kl[6,...]/(2*(kappaa + 1)**2 + 1) + 3*vp**2*md_kl[11,...]/(2*(kappaa + 1)**2 + 1) + 3*vs**2*(kappab + 1)**2*md_kl[20,...]/(2*(kappab + 1)**2 + 1) + (-3*gcp*vs**2/(2*(kappab + 1)**2 + 1) + 3*vs**2/(2*(kappab + 1)**2 + 1))*md_kl[15,...] + (3*gcp*vs**2/(2*(kappab + 1)**2 + 1) + 3*vs**2/(2*(kappab + 1)**2 + 1))*md_kl[18,...] + (3*vp**2*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1) - 6*vs**2*(kappab + 1)**2/(2*(kappab + 1)**2 + 1))*md_kl[1,...] + md_kl[21,...]
    kl_opt[3,...] = eta*(3*rho*vp**2*(-4*kappaa - 4)*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1)**2 + 3*rho*vp**2*(2*kappaa + 2)/(2*(kappaa + 1)**2 + 1))*md_kl[2,...] + eta*(3*rho*vp**2*(-4*kappaa - 4)*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1)**2 + 3*rho*vp**2*(2*kappaa + 2)/(2*(kappaa + 1)**2 + 1))*md_kl[7,...] + 3*rho*vp**2*(-4*kappaa - 4)*md_kl[11,...]/(2*(kappaa + 1)**2 + 1)**2 + (3*rho*vp**2*(-4*kappaa - 4)*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1)**2 + 3*rho*vp**2*(2*kappaa + 2)/(2*(kappaa + 1)**2 + 1))*md_kl[0,...] + (3*rho*vp**2*(-4*kappaa - 4)*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1)**2 + 3*rho*vp**2*(2*kappaa + 2)/(2*(kappaa + 1)**2 + 1))*md_kl[1,...] + (3*rho*vp**2*(-4*kappaa - 4)*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1)**2 + 3*rho*vp**2*(2*kappaa + 2)/(2*(kappaa + 1)**2 + 1))*md_kl[6,...]
    kl_opt[4,...] = -6*eta*rho*vs**2*(-4*kappab - 4)*md_kl[2,...]/(2*(kappab + 1)**2 + 1)**2 - 6*eta*rho*vs**2*(-4*kappab - 4)*md_kl[7,...]/(2*(kappab + 1)**2 + 1)**2 - 3*gsp*rho*vs**2*(-4*kappab - 4)*md_kl[16,...]/(2*(kappab + 1)**2 + 1)**2 + (-3*gcp*rho*vs**2*(-4*kappab - 4)/(2*(kappab + 1)**2 + 1)**2 + 3*rho*vs**2*(-4*kappab - 4)/(2*(kappab + 1)**2 + 1)**2)*md_kl[15,...] + (3*gcp*rho*vs**2*(-4*kappab - 4)/(2*(kappab + 1)**2 + 1)**2 + 3*rho*vs**2*(-4*kappab - 4)/(2*(kappab + 1)**2 + 1)**2)*md_kl[18,...] + (-6*rho*vs**2*(-4*kappab - 4)*(kappab + 1)**2/(2*(kappab + 1)**2 + 1)**2 - 6*rho*vs**2*(2*kappab + 2)/(2*(kappab + 1)**2 + 1))*md_kl[1,...] + (3*rho*vs**2*(-4*kappab - 4)*(kappab + 1)**2/(2*(kappab + 1)**2 + 1)**2 + 3*rho*vs**2*(2*kappab + 2)/(2*(kappab + 1)**2 + 1))*md_kl[20,...]
    kl_opt[5,...] = (3*rho*vp**2*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1) - 6*rho*vs**2/(2*(kappab + 1)**2 + 1))*md_kl[2,...] + (3*rho*vp**2*(kappaa + 1)**2/(2*(kappaa + 1)**2 + 1) - 6*rho*vs**2/(2*(kappab + 1)**2 + 1))*md_kl[7,...]
    kl_opt[6,...] = -3*rho*vs**2*md_kl[15,...]/(2*(kappab + 1)**2 + 1) + 3*rho*vs**2*md_kl[18,...]/(2*(kappab + 1)**2 + 1)
    kl_opt[7,...] = -3*rho*vs**2*md_kl[16,...]/(2*(kappab + 1)**2 + 1)
    kl_opt[0:3,...] *= md_usr[0:3,...]
    return kl_opt


MODEL_CONVERTERS = {
    1: cijkl2dtti_kltype1,
    2: cijkl2dtti_kltype2,
    3: cijkl2dtti_kltype3,
}

KERNEL_CONVERTERS = {
    1: kl2dtti_kltype1,
    2: kl2dtti_kltype2,
    3: kl2dtti_kltype3,
}
