"""
AUTO-GENERATED by auto_kergen.py -- do not edit by hand.
Regenerate with:  python auto_kergen.py --write

Base <-> user model and kernel conversions for the dtti model type.
"""
import numpy as np


def cijkl2dtti_kltype1(model, backward=False):
    if not backward:
        model_new = np.zeros((5,) + model.shape[1:])
        x0 = model[21,...]**(-1.0)
        x1 = model[20,...]**(-1.0)
        model_new[0,...] = np.sqrt(x0*model[0,...])
        model_new[1,...] = np.sqrt(x0*model[20,...])
        model_new[2,...] = model[21,...]
        model_new[3,...] = x1*(-1/2*model[15,...] + (1/2)*model[18,...])
        model_new[4,...] = -x1*model[16,...]
    else:
        vp = model[0,...]
        vs = model[1,...]
        rho = model[2,...]
        gcp = model[3,...]
        gsp = model[4,...]
        model_new = np.zeros((22,) + model.shape[1:])
        x0 = rho*vp**2
        x1 = vs**2
        x2 = rho*x1
        x3 = x0 - 2*x2
        x4 = gcp*x2
        model_new[0,...] = x0
        model_new[1,...] = x3
        model_new[2,...] = x3
        model_new[6,...] = x0
        model_new[7,...] = x3
        model_new[11,...] = x0
        model_new[15,...] = rho*x1 - x4
        model_new[16,...] = -gsp*x2
        model_new[18,...] = x2 + x4
        model_new[20,...] = x2
        model_new[21,...] = rho
    return model_new


def kl2dtti_kltype1(md_usr, md_kl):
    vp = md_usr[0,...]
    vs = md_usr[1,...]
    rho = md_usr[2,...]
    gcp = md_usr[3,...]
    gsp = md_usr[4,...]
    kl_opt = md_usr * 0
    x0 = 2*rho
    x1 = vp*x0
    x2 = 4*rho*vs
    x3 = vs*x0
    x4 = gcp*x3
    x5 = vp**2
    x6 = vs**2
    x7 = x6*md_kl[16,...]
    x8 = x5 - 2*x6
    x9 = gcp*x6
    kl_opt[0,...] = x1*md_kl[0,...] + x1*md_kl[11,...] + x1*md_kl[1,...] + x1*md_kl[2,...] + x1*md_kl[6,...] + x1*md_kl[7,...]
    kl_opt[1,...] = -gsp*x3*md_kl[16,...] + 2*rho*vs*md_kl[20,...] - x2*md_kl[1,...] - x2*md_kl[2,...] - x2*md_kl[7,...] + (x3 + x4)*md_kl[18,...] + (2*rho*vs - x4)*md_kl[15,...]
    kl_opt[2,...] = -gsp*x7 + x5*md_kl[0,...] + x5*md_kl[11,...] + x5*md_kl[6,...] + x6*md_kl[20,...] + x8*md_kl[1,...] + x8*md_kl[2,...] + x8*md_kl[7,...] + (x6 - x9)*md_kl[15,...] + (x6 + x9)*md_kl[18,...] + md_kl[21,...]
    kl_opt[3,...] = -rho*x6*md_kl[15,...] + rho*x6*md_kl[18,...]
    kl_opt[4,...] = -rho*x7
    kl_opt[0:3,...] *= md_usr[0:3,...]
    return kl_opt


def cijkl2dtti_kltype2(model, backward=False):
    if not backward:
        model_new = np.zeros((8,) + model.shape[1:])
        x0 = model[21,...]**(-1.0)
        x1 = (1/2)*model[15,...]
        x2 = x1 + (1/2)*model[18,...]
        x3 = x2**(-1.0)
        model_new[0,...] = np.sqrt(x0*model[0,...])
        model_new[1,...] = np.sqrt(x0*model[11,...])
        model_new[2,...] = np.sqrt(x0*model[20,...])
        model_new[3,...] = np.sqrt(x0*x2)
        model_new[4,...] = model[21,...]
        model_new[5,...] = model[2,...]/(model[0,...] - model[15,...] - model[18,...])
        model_new[6,...] = x3*(-x1 + (1/2)*model[18,...])
        model_new[7,...] = -x3*model[16,...]
    else:
        vph = model[0,...]
        vpv = model[1,...]
        vsh = model[2,...]
        vsv = model[3,...]
        rho = model[4,...]
        eta = model[5,...]
        gcp = model[6,...]
        gsp = model[7,...]
        model_new = np.zeros((22,) + model.shape[1:])
        x0 = rho*vph**2
        x1 = rho*vsh**2
        x2 = vsv**2
        x3 = rho*x2
        x4 = eta*(x0 - 2*x3)
        x5 = gcp*x3
        model_new[0,...] = x0
        model_new[1,...] = x0 - 2*x1
        model_new[2,...] = x4
        model_new[6,...] = x0
        model_new[7,...] = x4
        model_new[11,...] = rho*vpv**2
        model_new[15,...] = rho*x2 - x5
        model_new[16,...] = -gsp*x3
        model_new[18,...] = x3 + x5
        model_new[20,...] = x1
        model_new[21,...] = rho
    return model_new


def kl2dtti_kltype2(md_usr, md_kl):
    vph = md_usr[0,...]
    vpv = md_usr[1,...]
    vsh = md_usr[2,...]
    vsv = md_usr[3,...]
    rho = md_usr[4,...]
    eta = md_usr[5,...]
    gcp = md_usr[6,...]
    gsp = md_usr[7,...]
    kl_opt = md_usr * 0
    x0 = 2*rho
    x1 = vph*x0
    x2 = eta*x1
    x3 = 4*rho
    x4 = eta*vsv*x3
    x5 = vsv*x0
    x6 = gcp*x5
    x7 = vph**2
    x8 = vsh**2
    x9 = vsv**2
    x10 = x9*md_kl[16,...]
    x11 = gcp*x9
    x12 = 2*x9
    x13 = eta*(-x12 + x7)
    x14 = -rho*x12 + rho*x7
    kl_opt[0,...] = x1*md_kl[0,...] + x1*md_kl[1,...] + x1*md_kl[6,...] + x2*md_kl[2,...] + x2*md_kl[7,...]
    kl_opt[1,...] = vpv*x0*md_kl[11,...]
    kl_opt[2,...] = 2*rho*vsh*md_kl[20,...] - vsh*x3*md_kl[1,...]
    kl_opt[3,...] = -gsp*x5*md_kl[16,...] - x4*md_kl[2,...] - x4*md_kl[7,...] + (x5 + x6)*md_kl[18,...] + (2*rho*vsv - x6)*md_kl[15,...]
    kl_opt[4,...] = -gsp*x10 + vpv**2*md_kl[11,...] + x13*md_kl[2,...] + x13*md_kl[7,...] + x7*md_kl[0,...] + x7*md_kl[6,...] + x8*md_kl[20,...] + (-x11 + x9)*md_kl[15,...] + (x11 + x9)*md_kl[18,...] + (x7 - 2*x8)*md_kl[1,...] + md_kl[21,...]
    kl_opt[5,...] = x14*md_kl[2,...] + x14*md_kl[7,...]
    kl_opt[6,...] = -rho*x9*md_kl[15,...] + rho*x9*md_kl[18,...]
    kl_opt[7,...] = -rho*x10
    kl_opt[0:5,...] *= md_usr[0:5,...]
    return kl_opt


def cijkl2dtti_kltype3(model, backward=False):
    if not backward:
        model_new = np.zeros((8,) + model.shape[1:])
        x0 = model[21,...]**(-1.0)
        x1 = x0*model[0,...]
        x2 = x0*model[11,...]
        x3 = x0*model[20,...]
        x4 = (1/2)*model[15,...]
        x5 = x4 + (1/2)*model[18,...]
        x6 = x0*x5
        x7 = np.sqrt(x2)
        x8 = np.sqrt(x6)
        x9 = x5**(-1.0)
        model_new[0,...] = np.sqrt((2/3)*x1 + (1/3)*x2)
        model_new[1,...] = np.sqrt((2/3)*x3 + (1/3)*x6)
        model_new[2,...] = model[21,...]
        model_new[3,...] = (np.sqrt(x1) - x7)/x7
        model_new[4,...] = (np.sqrt(x3) - x8)/x8
        model_new[5,...] = model[2,...]/(model[0,...] - model[15,...] - model[18,...])
        model_new[6,...] = x9*(-x4 + (1/2)*model[18,...])
        model_new[7,...] = -x9*model[16,...]
    else:
        vp = model[0,...]
        vs = model[1,...]
        rho = model[2,...]
        kappaa = model[3,...]
        kappab = model[4,...]
        eta = model[5,...]
        gcp = model[6,...]
        gsp = model[7,...]
        model_new = np.zeros((22,) + model.shape[1:])
        x0 = (kappaa + 1)**2
        x1 = 3*rho*vp**2/(2*x0 + 1)
        x2 = x0*x1
        x3 = (kappab + 1)**2
        x4 = vs**2
        x5 = (2*x3 + 1)**(-1.0)
        x6 = rho*x4*x5
        x7 = 6*x6
        x8 = eta*(x2 - x7)
        x9 = 3*x6
        x10 = gcp*x9
        model_new[0,...] = x2
        model_new[1,...] = x2 - x3*x7
        model_new[2,...] = x8
        model_new[6,...] = x2
        model_new[7,...] = x8
        model_new[11,...] = x1
        model_new[15,...] = 3*rho*x4*x5 - x10
        model_new[16,...] = -gsp*x9
        model_new[18,...] = x10 + x9
        model_new[20,...] = x3*x9
        model_new[21,...] = rho
    return model_new


def kl2dtti_kltype3(md_usr, md_kl):
    vp = md_usr[0,...]
    vs = md_usr[1,...]
    rho = md_usr[2,...]
    kappaa = md_usr[3,...]
    kappab = md_usr[4,...]
    eta = md_usr[5,...]
    gcp = md_usr[6,...]
    gsp = md_usr[7,...]
    kl_opt = md_usr * 0
    x0 = (kappaa + 1)**2
    x1 = 2*x0 + 1
    x2 = x1**(-1.0)
    x3 = x2*md_kl[11,...]
    x4 = 6*rho
    x5 = vp*x4
    x6 = x0*x2
    x7 = x5*x6
    x8 = eta*md_kl[2,...]
    x9 = eta*md_kl[7,...]
    x10 = (kappab + 1)**2
    x11 = 2*x10 + 1
    x12 = x11**(-1.0)
    x13 = vs*x12
    x14 = 12*rho*x13
    x15 = x13*x4
    x16 = gsp*md_kl[16,...]
    x17 = gcp*x15
    x18 = 3*vp**2
    x19 = vs**2
    x20 = x12*x19
    x21 = 3*x20
    x22 = x21*md_kl[16,...]
    x23 = x18*x6
    x24 = gcp*x21
    x25 = 6*x20
    x26 = eta*(x23 - x25)
    x27 = rho*x18
    x28 = x27*(-4*kappaa - 4)/x1**2
    x29 = x0*x28 + x2*x27*(2*kappaa + 2)
    x30 = eta*x29
    x31 = x11**(-2.0)
    x32 = -4*kappab - 4
    x33 = x19*x31*x32
    x34 = x33*x4
    x35 = 3*rho*x33
    x36 = gcp*x35
    x37 = 2*kappab + 2
    x38 = rho*x25
    x39 = rho*x21
    x40 = rho*x23 - x38
    kl_opt[0,...] = x3*x5 + x7*x8 + x7*x9 + x7*md_kl[0,...] + x7*md_kl[1,...] + x7*md_kl[6,...]
    kl_opt[1,...] = 6*rho*vs*x10*x12*md_kl[20,...] - x10*x14*md_kl[1,...] - x14*x8 - x14*x9 - x15*x16 + (x15 + x17)*md_kl[18,...] + (6*rho*vs*x12 - x17)*md_kl[15,...]
    kl_opt[2,...] = -gsp*x22 + x10*x21*md_kl[20,...] + x18*x3 + x23*md_kl[0,...] + x23*md_kl[6,...] + x26*md_kl[2,...] + x26*md_kl[7,...] + (x21 + x24)*md_kl[18,...] + (-x10*x25 + x23)*md_kl[1,...] + (3*x12*x19 - x24)*md_kl[15,...] + md_kl[21,...]
    kl_opt[3,...] = x28*md_kl[11,...] + x29*md_kl[0,...] + x29*md_kl[1,...] + x29*md_kl[6,...] + x30*md_kl[2,...] + x30*md_kl[7,...]
    kl_opt[4,...] = -x16*x35 - x34*x8 - x34*x9 + (x35 + x36)*md_kl[18,...] + (-x10*x34 - x37*x38)*md_kl[1,...] + (x10*x35 + x37*x39)*md_kl[20,...] + (3*rho*x19*x31*x32 - x36)*md_kl[15,...]
    kl_opt[5,...] = x40*md_kl[2,...] + x40*md_kl[7,...]
    kl_opt[6,...] = 3*rho*x12*x19*md_kl[18,...] - x39*md_kl[15,...]
    kl_opt[7,...] = -rho*x22
    kl_opt[0:3,...] *= md_usr[0:3,...]
    return kl_opt


MODEL_CONVERTERS = {
    1: cijkl2dtti_kltype1,
    2: cijkl2dtti_kltype2,
    3: cijkl2dtti_kltype3,
}

KERNEL_CONVERTERS = {
    1: kl2dtti_kltype1,
    2: kl2dtti_kltype2,
    3: kl2dtti_kltype3,
}
