"""
AUTO-GENERATED by auto_kergen.py -- do not edit by hand.
Regenerate with:  python auto_kergen.py --write

Base <-> user model and kernel conversions for the dtti model type.

Each converter is a numba nopython scalar loop over grid points with CSE:
shared subexpressions are scalar floats (near-zero memory) and the compiled
single-pass loop is several times faster than vectorized numpy. Single
threaded, no fastmath -- results are bit-reproducible.
"""
import numpy as np
from numba import jit


@jit(nopython=True, cache=True)
def _model_fwd_kltype1(model, out):
    n = model.shape[1]
    for g in range(n):
        x0 = model[21, g]**(-1.0)
        x1 = model[20, g]**(-1.0)
        out[0, g] = np.sqrt(x0*model[0, g])
        out[1, g] = np.sqrt(x0*model[20, g])
        out[2, g] = model[21, g]
        out[3, g] = x1*(-1/2*model[15, g] + (1/2)*model[18, g])
        out[4, g] = -x1*model[16, g]

@jit(nopython=True, cache=True)
def _model_bwd_kltype1(model, out):
    n = model.shape[1]
    for g in range(n):
        vp = model[0, g]
        vs = model[1, g]
        rho = model[2, g]
        gcp = model[3, g]
        gsp = model[4, g]
        x0 = rho*vp**2
        x1 = vs**2
        x2 = rho*x1
        x3 = x0 - 2*x2
        x4 = gcp*x2
        out[0, g] = x0
        out[1, g] = x3
        out[2, g] = x3
        out[6, g] = x0
        out[7, g] = x3
        out[11, g] = x0
        out[15, g] = rho*x1 - x4
        out[16, g] = -gsp*x2
        out[18, g] = x2 + x4
        out[20, g] = x2
        out[21, g] = rho

def cijkl2dtti_kltype1(model, backward=False):
    shp = model.shape
    m2 = np.ascontiguousarray(model).reshape(shp[0], -1)
    ncol = m2.shape[1]
    if not backward:
        out = np.zeros((5, ncol), dtype=np.float64)
        _model_fwd_kltype1(m2, out)
        return out.reshape((5,) + shp[1:])
    else:
        out = np.zeros((22, ncol), dtype=np.float64)
        _model_bwd_kltype1(m2, out)
        return out.reshape((22,) + shp[1:])


@jit(nopython=True, cache=True)
def _kl_core_kltype1(md_usr, md_kl, kl_opt):
    n = md_usr.shape[1]
    for g in range(n):
        vp = md_usr[0, g]
        vs = md_usr[1, g]
        rho = md_usr[2, g]
        gcp = md_usr[3, g]
        gsp = md_usr[4, g]
        x0 = 2*rho
        x1 = vp*x0
        x2 = 4*rho*vs
        x3 = vs*x0
        x4 = gcp*x3
        x5 = vp**2
        x6 = vs**2
        x7 = x6*md_kl[16, g]
        x8 = x5 - 2*x6
        x9 = gcp*x6
        kl_opt[0, g] = x1*md_kl[0, g] + x1*md_kl[11, g] + x1*md_kl[1, g] + x1*md_kl[2, g] + x1*md_kl[6, g] + x1*md_kl[7, g]
        kl_opt[1, g] = -gsp*x3*md_kl[16, g] + 2*rho*vs*md_kl[20, g] - x2*md_kl[1, g] - x2*md_kl[2, g] - x2*md_kl[7, g] + (x3 + x4)*md_kl[18, g] + (2*rho*vs - x4)*md_kl[15, g]
        kl_opt[2, g] = -gsp*x7 + x5*md_kl[0, g] + x5*md_kl[11, g] + x5*md_kl[6, g] + x6*md_kl[20, g] + x8*md_kl[1, g] + x8*md_kl[2, g] + x8*md_kl[7, g] + (x6 - x9)*md_kl[15, g] + (x6 + x9)*md_kl[18, g] + md_kl[21, g]
        kl_opt[3, g] = -rho*x6*md_kl[15, g] + rho*x6*md_kl[18, g]
        kl_opt[4, g] = -rho*x7
        for j in range(3):
            kl_opt[j, g] *= md_usr[j, g]

def kl2dtti_kltype1(md_usr, md_kl):
    shp = md_usr.shape
    mu = np.ascontiguousarray(md_usr).reshape(shp[0], -1)
    mk = np.ascontiguousarray(md_kl).reshape(md_kl.shape[0], -1)
    kl_opt = np.zeros_like(mu)
    _kl_core_kltype1(mu, mk, kl_opt)
    return kl_opt.reshape(shp)


@jit(nopython=True, cache=True)
def _model_fwd_kltype2(model, out):
    n = model.shape[1]
    for g in range(n):
        x0 = model[21, g]**(-1.0)
        x1 = (1/2)*model[15, g]
        x2 = x1 + (1/2)*model[18, g]
        x3 = x2**(-1.0)
        out[0, g] = np.sqrt(x0*model[0, g])
        out[1, g] = np.sqrt(x0*model[11, g])
        out[2, g] = np.sqrt(x0*model[20, g])
        out[3, g] = np.sqrt(x0*x2)
        out[4, g] = model[21, g]
        out[5, g] = model[2, g]/(model[0, g] - model[15, g] - model[18, g])
        out[6, g] = x3*(-x1 + (1/2)*model[18, g])
        out[7, g] = -x3*model[16, g]

@jit(nopython=True, cache=True)
def _model_bwd_kltype2(model, out):
    n = model.shape[1]
    for g in range(n):
        vph = model[0, g]
        vpv = model[1, g]
        vsh = model[2, g]
        vsv = model[3, g]
        rho = model[4, g]
        eta = model[5, g]
        gcp = model[6, g]
        gsp = model[7, g]
        x0 = rho*vph**2
        x1 = rho*vsh**2
        x2 = vsv**2
        x3 = rho*x2
        x4 = eta*(x0 - 2*x3)
        x5 = gcp*x3
        out[0, g] = x0
        out[1, g] = x0 - 2*x1
        out[2, g] = x4
        out[6, g] = x0
        out[7, g] = x4
        out[11, g] = rho*vpv**2
        out[15, g] = rho*x2 - x5
        out[16, g] = -gsp*x3
        out[18, g] = x3 + x5
        out[20, g] = x1
        out[21, g] = rho

def cijkl2dtti_kltype2(model, backward=False):
    shp = model.shape
    m2 = np.ascontiguousarray(model).reshape(shp[0], -1)
    ncol = m2.shape[1]
    if not backward:
        out = np.zeros((8, ncol), dtype=np.float64)
        _model_fwd_kltype2(m2, out)
        return out.reshape((8,) + shp[1:])
    else:
        out = np.zeros((22, ncol), dtype=np.float64)
        _model_bwd_kltype2(m2, out)
        return out.reshape((22,) + shp[1:])


@jit(nopython=True, cache=True)
def _kl_core_kltype2(md_usr, md_kl, kl_opt):
    n = md_usr.shape[1]
    for g in range(n):
        vph = md_usr[0, g]
        vpv = md_usr[1, g]
        vsh = md_usr[2, g]
        vsv = md_usr[3, g]
        rho = md_usr[4, g]
        eta = md_usr[5, g]
        gcp = md_usr[6, g]
        gsp = md_usr[7, g]
        x0 = 2*rho
        x1 = vph*x0
        x2 = eta*x1
        x3 = 4*rho
        x4 = eta*vsv*x3
        x5 = vsv*x0
        x6 = gcp*x5
        x7 = vph**2
        x8 = vsh**2
        x9 = vsv**2
        x10 = x9*md_kl[16, g]
        x11 = gcp*x9
        x12 = 2*x9
        x13 = eta*(-x12 + x7)
        x14 = -rho*x12 + rho*x7
        kl_opt[0, g] = x1*md_kl[0, g] + x1*md_kl[1, g] + x1*md_kl[6, g] + x2*md_kl[2, g] + x2*md_kl[7, g]
        kl_opt[1, g] = vpv*x0*md_kl[11, g]
        kl_opt[2, g] = 2*rho*vsh*md_kl[20, g] - vsh*x3*md_kl[1, g]
        kl_opt[3, g] = -gsp*x5*md_kl[16, g] - x4*md_kl[2, g] - x4*md_kl[7, g] + (x5 + x6)*md_kl[18, g] + (2*rho*vsv - x6)*md_kl[15, g]
        kl_opt[4, g] = -gsp*x10 + vpv**2*md_kl[11, g] + x13*md_kl[2, g] + x13*md_kl[7, g] + x7*md_kl[0, g] + x7*md_kl[6, g] + x8*md_kl[20, g] + (-x11 + x9)*md_kl[15, g] + (x11 + x9)*md_kl[18, g] + (x7 - 2*x8)*md_kl[1, g] + md_kl[21, g]
        kl_opt[5, g] = x14*md_kl[2, g] + x14*md_kl[7, g]
        kl_opt[6, g] = -rho*x9*md_kl[15, g] + rho*x9*md_kl[18, g]
        kl_opt[7, g] = -rho*x10
        for j in range(5):
            kl_opt[j, g] *= md_usr[j, g]

def kl2dtti_kltype2(md_usr, md_kl):
    shp = md_usr.shape
    mu = np.ascontiguousarray(md_usr).reshape(shp[0], -1)
    mk = np.ascontiguousarray(md_kl).reshape(md_kl.shape[0], -1)
    kl_opt = np.zeros_like(mu)
    _kl_core_kltype2(mu, mk, kl_opt)
    return kl_opt.reshape(shp)


@jit(nopython=True, cache=True)
def _model_fwd_kltype3(model, out):
    n = model.shape[1]
    for g in range(n):
        x0 = model[21, g]**(-1.0)
        x1 = x0*model[0, g]
        x2 = x0*model[11, g]
        x3 = x0*model[20, g]
        x4 = (1/2)*model[15, g]
        x5 = x4 + (1/2)*model[18, g]
        x6 = x0*x5
        x7 = np.sqrt(x2)
        x8 = np.sqrt(x6)
        x9 = x5**(-1.0)
        out[0, g] = np.sqrt((2/3)*x1 + (1/3)*x2)
        out[1, g] = np.sqrt((2/3)*x3 + (1/3)*x6)
        out[2, g] = model[21, g]
        out[3, g] = (np.sqrt(x1) - x7)/x7
        out[4, g] = (np.sqrt(x3) - x8)/x8
        out[5, g] = model[2, g]/(model[0, g] - model[15, g] - model[18, g])
        out[6, g] = x9*(-x4 + (1/2)*model[18, g])
        out[7, g] = -x9*model[16, g]

@jit(nopython=True, cache=True)
def _model_bwd_kltype3(model, out):
    n = model.shape[1]
    for g in range(n):
        vp = model[0, g]
        vs = model[1, g]
        rho = model[2, g]
        kappaa = model[3, g]
        kappab = model[4, g]
        eta = model[5, g]
        gcp = model[6, g]
        gsp = model[7, g]
        x0 = (kappaa + 1)**2
        x1 = 3*rho*vp**2/(2*x0 + 1)
        x2 = x0*x1
        x3 = (kappab + 1)**2
        x4 = vs**2
        x5 = (2*x3 + 1)**(-1.0)
        x6 = rho*x4*x5
        x7 = 6*x6
        x8 = eta*(x2 - x7)
        x9 = 3*x6
        x10 = gcp*x9
        out[0, g] = x2
        out[1, g] = x2 - x3*x7
        out[2, g] = x8
        out[6, g] = x2
        out[7, g] = x8
        out[11, g] = x1
        out[15, g] = 3*rho*x4*x5 - x10
        out[16, g] = -gsp*x9
        out[18, g] = x10 + x9
        out[20, g] = x3*x9
        out[21, g] = rho

def cijkl2dtti_kltype3(model, backward=False):
    shp = model.shape
    m2 = np.ascontiguousarray(model).reshape(shp[0], -1)
    ncol = m2.shape[1]
    if not backward:
        out = np.zeros((8, ncol), dtype=np.float64)
        _model_fwd_kltype3(m2, out)
        return out.reshape((8,) + shp[1:])
    else:
        out = np.zeros((22, ncol), dtype=np.float64)
        _model_bwd_kltype3(m2, out)
        return out.reshape((22,) + shp[1:])


@jit(nopython=True, cache=True)
def _kl_core_kltype3(md_usr, md_kl, kl_opt):
    n = md_usr.shape[1]
    for g in range(n):
        vp = md_usr[0, g]
        vs = md_usr[1, g]
        rho = md_usr[2, g]
        kappaa = md_usr[3, g]
        kappab = md_usr[4, g]
        eta = md_usr[5, g]
        gcp = md_usr[6, g]
        gsp = md_usr[7, g]
        x0 = (kappaa + 1)**2
        x1 = 2*x0 + 1
        x2 = x1**(-1.0)
        x3 = x2*md_kl[11, g]
        x4 = 6*rho
        x5 = vp*x4
        x6 = x0*x2
        x7 = x5*x6
        x8 = eta*md_kl[2, g]
        x9 = eta*md_kl[7, g]
        x10 = (kappab + 1)**2
        x11 = 2*x10 + 1
        x12 = x11**(-1.0)
        x13 = vs*x12
        x14 = 12*rho*x13
        x15 = x13*x4
        x16 = gsp*md_kl[16, g]
        x17 = gcp*x15
        x18 = 3*vp**2
        x19 = vs**2
        x20 = x12*x19
        x21 = 3*x20
        x22 = x21*md_kl[16, g]
        x23 = x18*x6
        x24 = gcp*x21
        x25 = 6*x20
        x26 = eta*(x23 - x25)
        x27 = rho*x18
        x28 = x27*(-4*kappaa - 4)/x1**2
        x29 = x0*x28 + x2*x27*(2*kappaa + 2)
        x30 = eta*x29
        x31 = x11**(-2.0)
        x32 = -4*kappab - 4
        x33 = x19*x31*x32
        x34 = x33*x4
        x35 = 3*rho*x33
        x36 = gcp*x35
        x37 = 2*kappab + 2
        x38 = rho*x25
        x39 = rho*x21
        x40 = rho*x23 - x38
        kl_opt[0, g] = x3*x5 + x7*x8 + x7*x9 + x7*md_kl[0, g] + x7*md_kl[1, g] + x7*md_kl[6, g]
        kl_opt[1, g] = 6*rho*vs*x10*x12*md_kl[20, g] - x10*x14*md_kl[1, g] - x14*x8 - x14*x9 - x15*x16 + (x15 + x17)*md_kl[18, g] + (6*rho*vs*x12 - x17)*md_kl[15, g]
        kl_opt[2, g] = -gsp*x22 + x10*x21*md_kl[20, g] + x18*x3 + x23*md_kl[0, g] + x23*md_kl[6, g] + x26*md_kl[2, g] + x26*md_kl[7, g] + (x21 + x24)*md_kl[18, g] + (-x10*x25 + x23)*md_kl[1, g] + (3*x12*x19 - x24)*md_kl[15, g] + md_kl[21, g]
        kl_opt[3, g] = x28*md_kl[11, g] + x29*md_kl[0, g] + x29*md_kl[1, g] + x29*md_kl[6, g] + x30*md_kl[2, g] + x30*md_kl[7, g]
        kl_opt[4, g] = -x16*x35 - x34*x8 - x34*x9 + (x35 + x36)*md_kl[18, g] + (-x10*x34 - x37*x38)*md_kl[1, g] + (x10*x35 + x37*x39)*md_kl[20, g] + (3*rho*x19*x31*x32 - x36)*md_kl[15, g]
        kl_opt[5, g] = x40*md_kl[2, g] + x40*md_kl[7, g]
        kl_opt[6, g] = 3*rho*x12*x19*md_kl[18, g] - x39*md_kl[15, g]
        kl_opt[7, g] = -rho*x22
        for j in range(3):
            kl_opt[j, g] *= md_usr[j, g]

def kl2dtti_kltype3(md_usr, md_kl):
    shp = md_usr.shape
    mu = np.ascontiguousarray(md_usr).reshape(shp[0], -1)
    mk = np.ascontiguousarray(md_kl).reshape(md_kl.shape[0], -1)
    kl_opt = np.zeros_like(mu)
    _kl_core_kltype3(mu, mk, kl_opt)
    return kl_opt.reshape(shp)


MODEL_CONVERTERS = {
    1: cijkl2dtti_kltype1,
    2: cijkl2dtti_kltype2,
    3: cijkl2dtti_kltype3,
}

KERNEL_CONVERTERS = {
    1: kl2dtti_kltype1,
    2: kl2dtti_kltype2,
    3: kl2dtti_kltype3,
}
